import AppKit
import Combine
import Foundation
import UniformTypeIdentifiers

extension ClipboardHistoryViewModel {
    func loadHistoryAndStartMonitoring() async {
        await loadHistory()
        startMonitoring()
        AppLog.lifecycle.notice("Clipboard history ready; persistedCount=\(self.items.count)")
    }

    func observeSharedState() {
        settingsCancellable = settings.objectWillChange.sink { [weak self] in
            Task { @MainActor in
                await Task.yield()
                guard self?.isShuttingDown == false else { return }
                self?.settingsDidChange()
            }
        }
        lockCancellable = lockService.$state.dropFirst().sink { [weak self] state in
            self?.objectWillChange.send()
            if state.isLocked {
                self?.isShowingSensitiveSaveConfirmation = false
                self?.endPanelModalInteraction?()
                Task { await self?.thumbnailService.clearCache() }
            } else {
                self?.presentNextSensitiveConfirmationIfUnlocked()
            }
        }
    }

    func updateIgnoredPasteboardTypes() {
        monitor.ignoredPasteboardTypes = Set([
            "org.nspasteboard.transienttype",
            "org.nspasteboard.concealedtype",
            "org.nspasteboard.autogeneratedtype"
        ]).union(settings.ignoredPasteboardTypes)
    }

    func shouldCapture(from bundleIdentifier: String?) -> Bool {
        guard !isPaused else { return false }
        guard !isLocked || settings.captureWhileLocked else { return false }
        guard let bundle = bundleIdentifier?.lowercased() else { return true }
        if settings.allowedBundleIdentifiers.contains(bundle) { return true }
        return !settings.excludedBundleIdentifiers.contains(bundle)
    }

    func sensitivityResult(
        for content: ClipboardContent,
        analysis: ClipboardContentAnalysis
    ) -> SecretDetectionResult {
        guard settings.secretDetectionEnabled else {
            return SecretDetectionResult(isSensitive: false, confidence: 0, signals: [])
        }
        let source = content.sourceBundleIdentifier
        let values: [String]
        switch content {
        case let .text(value, _, _, _, _, _):
            values = [value]
        case .images, .pdf, .files:
            values = [analysis.extractedText, analysis.qrCodeText].compactMap { $0 }
        }
        return values.map {
            secretDetector.detect(in: $0, sourceBundleIdentifier: source)
        }.max(by: { $0.confidence < $1.confidence })
            ?? SecretDetectionResult(isSensitive: false, confidence: 0, signals: [])
    }

    func makeItem(
        from content: ClipboardContent,
        sensitive: Bool,
        temporary: Bool,
        encrypted: Bool,
        analysis: ClipboardContentAnalysis = .empty
    ) async -> ClipboardItem? {
        let id = UUID()
        let expiresAt = temporary
            ? Date.now.addingTimeInterval(Double(settings.sensitiveRetentionSeconds))
            : nil

        switch content {
        case let .text(value, rtfData, htmlData, subtype, hash, source):
            var payloadFilename: String?
            var itemType: ClipboardItemType = .text
            if !temporary, (htmlData != nil || rtfData != nil), settings.captureRichText {
                let payload = RichTextPayload(rtfData: rtfData, htmlData: htmlData)
                guard let payloadData = try? JSONEncoder().encode(payload) else { return nil }
                payloadFilename = await storage.storePayload(
                    payloadData,
                    id: id,
                    extension: "rich",
                    encrypt: encrypted
                )
                itemType = .richText
            }
            return ClipboardItem(
                id: id,
                type: itemType,
                text: value,
                hash: hash,
                displayTitle: value.split(separator: "\n", maxSplits: 1).first.map(String.init),
                contentSubtype: subtype,
                expiresAt: expiresAt,
                isSensitive: sensitive,
                sourceApplicationBundleID: source,
                payloadFilename: payloadFilename,
                fileSize: Int64(value.utf8.count + (rtfData?.count ?? 0) + (htmlData?.count ?? 0)),
                isEncrypted: encrypted,
                protectedMetadata: ClipboardProtectedMetadata(
                    displayTitle: value.split(separator: "\n", maxSplits: 1).first.map(String.init),
                    colorHex: analysis.colorHex
                )
            )

        case let .images(pngData, hash, source):
            guard !temporary else { return nil }
            let dimensions = await metadataExtractor.dimensions(forFirstImage: pngData)
            var filenames: [String] = []
            for (index, data) in pngData.enumerated() {
                guard let filename = await storage.storeImage(
                    data,
                    id: id,
                    encrypt: encrypted,
                    index: pngData.count == 1 ? nil : index
                ) else {
                    let partial = ClipboardItem(
                        id: id,
                        type: .imageGroup,
                        hash: hash,
                        assetFilenames: filenames,
                        isEncrypted: encrypted
                    )
                    await storage.deleteImages(for: [partial])
                    return nil
                }
                filenames.append(filename)
            }
            let thumbnailFilename = "\(id.uuidString.lowercased())-thumb.png"
            let isGroup = pngData.count > 1
            return ClipboardItem(
                id: id,
                type: isGroup ? .imageGroup : .image,
                imageFilename: isGroup ? nil : filenames.first,
                hash: hash,
                displayTitle: isGroup ? "\(pngData.count) Images" : "Image",
                thumbnailFilename: thumbnailFilename,
                contentSubtype: isGroup ? .imageGroup : .image,
                isSensitive: sensitive,
                sourceApplicationBundleID: source,
                assetFilenames: isGroup ? filenames : [],
                imageWidth: dimensions?.width,
                imageHeight: dimensions?.height,
                fileSize: Int64(pngData.reduce(0) { $0 + $1.count }),
                isEncrypted: encrypted,
                protectedMetadata: ClipboardProtectedMetadata(
                    displayTitle: isGroup ? "\(pngData.count) Images" : "Image",
                    extractedText: analysis.extractedText,
                    qrCodeText: analysis.qrCodeText
                )
            )

        case let .pdf(data, hash, source):
            guard settings.capturePDFs,
                  !temporary,
                  let filename = await storage.storePayload(
                      data,
                      id: id,
                      extension: "pdf",
                      encrypt: encrypted
                  ) else { return nil }
            let pageCount = await metadataExtractor.pageCount(forPDF: data)
            return ClipboardItem(
                id: id,
                type: .pdf,
                hash: hash,
                displayTitle: "PDF Document",
                thumbnailFilename: "\(id.uuidString.lowercased())-thumb.png",
                contentSubtype: .pdf,
                isSensitive: sensitive,
                sourceApplicationBundleID: source,
                payloadFilename: filename,
                pageCount: pageCount,
                fileSize: Int64(data.count),
                isEncrypted: encrypted
            )

        case let .files(urls, bookmarks, hash, source):
            guard settings.captureFiles, !temporary else { return nil }
            let firstName = urls.first?.lastPathComponent ?? "Files"
            return ClipboardItem(
                id: id,
                type: .files,
                hash: hash,
                displayTitle: urls.count == 1 ? firstName : "\(firstName) and \(urls.count - 1) more",
                contentSubtype: urls.count == 1 ? .file : .files,
                isSensitive: sensitive,
                sourceApplicationBundleID: source,
                fileURLs: urls.map(\.path),
                fileBookmarks: bookmarks,
                fileSize: urls.reduce(Int64(0)) { result, url in
                    let size = (try? url.resourceValues(forKeys: [.fileSizeKey]).fileSize) ?? 0
                    return result + Int64(size)
                },
                isEncrypted: encrypted
            )
        }
    }

    func duplicateItem(hash: String) -> ClipboardItem? {
        switch settings.duplicateDetectionScope {
        case .newest:
            guard items.first?.hash == hash else { return nil }
            return items.first
        case .lastTen:
            return items.prefix(10).first { $0.hash == hash }
        case .lastHour:
            let cutoff = Date.now.addingTimeInterval(-3_600)
            return items.first { $0.creationDate >= cutoff && $0.hash == hash }
        case .fullHistory:
            return items.first { $0.hash == hash }
        }
    }

    func associateExistingItem(
        hash: String,
        with identity: ClipboardPasteboardIdentity
    ) {
        guard let item = items.first(where: { $0.hash == hash }) else { return }
        pasteboardIdentityByItemID[item.id] = identity
    }

    func clearCurrentPasteboardIfNeeded(for item: ClipboardItem) {
        guard let identity = pasteboardIdentityByItemID[item.id],
              monitor.clearCurrentContent(if: identity) else { return }
        pasteboardIdentityByItemID = pasteboardIdentityByItemID.filter { $0.value != identity }
        if lastProgrammaticallyWrittenIdentity == identity {
            lastProgrammaticallyWrittenHash = nil
            lastProgrammaticallyWrittenIdentity = nil
        }
    }

    func scheduleExpiration(for item: ClipboardItem) {
        guard let expiresAt = item.expiresAt else { return }
        expirationTasks[item.id]?.cancel()
        expirationTasks[item.id] = Task { [weak self] in
            let seconds = max(0, expiresAt.timeIntervalSinceNow)
            do {
                try await self?.sleepClock.sleep(for: .seconds(seconds))
                guard let self, !Task.isCancelled else { return }
                temporaryContent[item.id] = nil
                pasteboardIdentityByItemID[item.id] = nil
                pendingSensitiveItemIDs.removeAll { $0 == item.id }
                items.removeAll { $0.id == item.id }
                expirationTasks[item.id] = nil
                refreshDisplayedItems()
                presentNextSensitiveConfirmationIfUnlocked()
            } catch {
                // Cancellation means the item was removed or the app is terminating.
            }
        }
    }

}
