import AppKit
import XCTest
@testable import ClipboardHistory

@MainActor
final class ClipboardMonitorTests: XCTestCase, ClipboardMonitorDelegate {
    private var pasteboard: NSPasteboard!
    private var monitor: ClipboardMonitor!
    private var receivedContent: ClipboardContent?
    private var receivedIdentity: ClipboardPasteboardIdentity?

    private func prepareMonitor() {
        pasteboard = NSPasteboard(name: .init("ClipboardMonitorTests-\(UUID().uuidString)"))
        monitor = ClipboardMonitor(pasteboard: pasteboard)
        monitor.delegate = self
        receivedContent = nil
        receivedIdentity = nil
    }

    func testPollingIntervalIsHalfASecond() {
        XCTAssertEqual(ClipboardMonitor.pollingInterval, 0.5)
    }

    func testMonitorDoesNotRetainItselfThroughTimer() {
        weak var weakMonitor: ClipboardMonitor?

        autoreleasepool {
            var instance: ClipboardMonitor? = ClipboardMonitor(
                pasteboard: NSPasteboard(name: .init("MonitorLifetimeTests"))
            )
            weakMonitor = instance
            instance?.start()
            instance = nil
        }

        XCTAssertNil(weakMonitor)
    }

    func testReadsTextClipboardContent() async {
        prepareMonitor()
        pasteboard.clearContents()
        pasteboard.setString("copied text", forType: .string)

        await monitor.pollNowAndWait()

        guard case let .text(value, _, _, subtype, hash, _) = receivedContent else {
            return XCTFail("Expected text clipboard content")
        }
        XCTAssertEqual(value, "copied text")
        XCTAssertEqual(subtype, .plainText)
        XCTAssertEqual(hash, HashUtility.sha256(text: "copied text"))
        XCTAssertEqual(receivedIdentity?.changeCount, pasteboard.changeCount)
    }

    func testPrefersPNGOverText() async throws {
        prepareMonitor()
        let pngData = try XCTUnwrap(makePNGData())
        pasteboard.clearContents()
        pasteboard.setString("lower priority", forType: .string)
        pasteboard.setData(pngData, forType: .png)

        await monitor.pollNowAndWait()

        guard case let .images(images, hash, _) = receivedContent else {
            return XCTFail("Expected image clipboard content")
        }
        XCTAssertEqual(images, [pngData])
        XCTAssertEqual(hash, HashUtility.sha256(data: pngData))
    }

    func testConvertsTIFFClipboardContentToPNG() async throws {
        prepareMonitor()
        let image = NSImage(size: NSSize(width: 2, height: 2))
        image.lockFocus()
        NSColor(deviceRed: 0.9, green: 0.1, blue: 0.1, alpha: 1).setFill()
        NSRect(origin: .zero, size: image.size).fill()
        image.unlockFocus()
        let tiffData = try XCTUnwrap(image.tiffRepresentation)

        pasteboard.clearContents()
        pasteboard.setData(tiffData, forType: .tiff)
        await monitor.pollNowAndWait()

        guard case let .images(pngDataGroup, hash, _) = receivedContent,
              let pngData = pngDataGroup.first else {
            return XCTFail("Expected converted image clipboard content")
        }
        XCTAssertTrue(pngData.starts(with: [0x89, 0x50, 0x4E, 0x47]))
        XCTAssertEqual(hash, HashUtility.sha256(data: pngData))
    }

    func testMatchingIdentityClearsCurrentPasteboardSynchronously() {
        prepareMonitor()
        pasteboard.clearContents()
        pasteboard.setString("current", forType: .string)
        let identity = monitor.currentIdentity

        XCTAssertTrue(monitor.clearCurrentContent(if: identity))
        XCTAssertNil(pasteboard.string(forType: .string))
    }

    func testStaleIdentityDoesNotClearNewPasteboardContent() {
        prepareMonitor()
        pasteboard.clearContents()
        pasteboard.setString("old", forType: .string)
        let staleIdentity = monitor.currentIdentity
        pasteboard.clearContents()
        pasteboard.setString("new", forType: .string)

        XCTAssertFalse(monitor.clearCurrentContent(if: staleIdentity))
        XCTAssertEqual(pasteboard.string(forType: .string), "new")
    }

    func testTransientConcealedAndAutoGeneratedTypesAreAlwaysIgnored() async {
        for identifier in [
            "org.nspasteboard.TransientType",
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.AutoGeneratedType"
        ] {
            prepareMonitor()
            let ignoredType = NSPasteboard.PasteboardType(identifier)
            pasteboard.declareTypes([.string, ignoredType], owner: nil)
            pasteboard.setString("must not be captured", forType: .string)
            pasteboard.setString("1", forType: ignoredType)

            await monitor.pollNowAndWait()

            XCTAssertNil(receivedContent, "Captured ignored type: \(identifier)")
        }
    }

    func testUniversalAndCustomTypesCanBeIgnored() async {
        for identifier in ["com.apple.is-remote-clipboard", "com.example.private-copy"] {
            prepareMonitor()
            monitor.ignoredPasteboardTypes.insert(identifier)
            let ignoredType = NSPasteboard.PasteboardType(identifier)
            pasteboard.declareTypes([.string, ignoredType], owner: nil)
            pasteboard.setString("must not be captured", forType: .string)
            pasteboard.setString("1", forType: ignoredType)

            await monitor.pollNowAndWait()

            XCTAssertNil(receivedContent, "Captured user-ignored type: \(identifier)")
        }
    }

    func testIgnoreNextCopyConsumesExactlyOneChange() async {
        prepareMonitor()
        monitor.ignoreNextCopy()
        pasteboard.clearContents()
        pasteboard.setString("ignored once", forType: .string)
        await monitor.pollNowAndWait()
        XCTAssertNil(receivedContent)

        pasteboard.clearContents()
        pasteboard.setString("captured next", forType: .string)
        await monitor.pollNowAndWait()

        guard case let .text(value, _, _, _, _, _) = receivedContent else {
            return XCTFail("Expected the second change to be captured")
        }
        XCTAssertEqual(value, "captured next")
    }

    func testStartStopAndPollWrapperUseInjectedScheduler() async {
        let pasteboard = NSPasteboard(name: .init("ClipboardMonitorScheduler-\(UUID().uuidString)"))
        let scheduler = MonitorTimerSchedulerSpy()
        let monitor = ClipboardMonitor(pasteboard: pasteboard, timerScheduler: scheduler)
        monitor.delegate = self

        monitor.start()
        monitor.start()
        XCTAssertEqual(scheduler.scheduleCount, 1)
        XCTAssertEqual(scheduler.interval, ClipboardMonitor.pollingInterval)
        XCTAssertEqual(scheduler.tolerance, 0.1)
        pasteboard.clearContents()
        pasteboard.setString("wrapper poll", forType: .string)
        scheduler.fire()
        for _ in 0..<100 where receivedContent == nil { await Task.yield() }
        guard case let .text(value, _, _, _, _, _) = receivedContent else {
            return XCTFail("Expected scheduled poll content")
        }
        XCTAssertEqual(value, "wrapper poll")

        monitor.stop()
        monitor.stop()
        XCTAssertEqual(scheduler.token.cancelCount, 1)
    }

    func testPDFFileRTFAndHTMLFallbackRepresentations() async throws {
        prepareMonitor()
        let pdf = Data("%PDF-1.7\nmonitor".utf8)
        pasteboard.clearContents()
        pasteboard.setData(pdf, forType: .pdf)
        await monitor.pollNowAndWait()
        guard case let .pdf(data, hash, _) = receivedContent else {
            return XCTFail("Expected PDF")
        }
        XCTAssertEqual(data, pdf)
        XCTAssertEqual(hash, HashUtility.sha256(data: pdf))

        prepareMonitor()
        let file = FileManager.default.temporaryDirectory.appending(
            path: "ClipboardMonitor-\(UUID().uuidString).txt"
        )
        try Data("file".utf8).write(to: file)
        defer { try? FileManager.default.removeItem(at: file) }
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.writeObjects([file as NSURL]))
        await monitor.pollNowAndWait()
        guard case let .files(urls, _, _, _) = receivedContent else {
            return XCTFail("Expected files")
        }
        XCTAssertEqual(urls, [file])

        prepareMonitor()
        let attributed = NSAttributedString(string: "RTF fallback")
        let rtf = try attributed.data(
            from: NSRange(location: 0, length: attributed.length),
            documentAttributes: [.documentType: NSAttributedString.DocumentType.rtf]
        )
        XCTAssertEqual(
            monitor.plainTextFallback(rtfData: rtf, htmlData: nil),
            "RTF fallback"
        )
        pasteboard.clearContents()
        pasteboard.setData(rtf, forType: .rtf)
        await monitor.pollNowAndWait()
        guard case let .text(rtfText, _, _, _, _, _) = receivedContent else {
            return XCTFail("Expected RTF fallback")
        }
        XCTAssertEqual(rtfText, "RTF fallback")

        prepareMonitor()
        pasteboard.clearContents()
        pasteboard.setData(Data("<p>HTML fallback</p>".utf8), forType: .html)
        await monitor.pollNowAndWait()
        guard case let .text(htmlText, _, _, _, _, _) = receivedContent else {
            return XCTFail("Expected HTML fallback")
        }
        XCTAssertEqual(htmlText, "HTML fallback")
    }

    func testNoChangeExcludedUnsupportedAndViewModelDelegatePaths() async throws {
        prepareMonitor()
        await monitor.pollNowAndWait()
        XCTAssertNil(receivedContent)

        monitor.shouldCaptureFromApplication = { _ in false }
        pasteboard.clearContents()
        pasteboard.setString("excluded", forType: .string)
        await monitor.pollNowAndWait()
        XCTAssertNil(receivedContent)

        prepareMonitor()
        pasteboard.declareTypes([.init("com.example.unsupported")], owner: nil)
        pasteboard.setData(Data("unsupported".utf8), forType: .init("com.example.unsupported"))
        await monitor.pollNowAndWait()
        XCTAssertNil(receivedContent)

        let directory = FileManager.default.temporaryDirectory.appending(
            path: "ClipboardMonitorDelegate-\(UUID().uuidString)",
            directoryHint: .isDirectory
        )
        let suite = "ClipboardMonitorDelegateDefaults-\(UUID().uuidString)"
        let defaults = try XCTUnwrap(UserDefaults(suiteName: suite))
        let delegatePasteboard = NSPasteboard(name: .init("ClipboardMonitorDelegate-\(UUID().uuidString)"))
        let delegateMonitor = ClipboardMonitor(pasteboard: delegatePasteboard)
        let storage = StorageService(baseDirectory: directory, encryptionService: .ephemeral())
        let viewModel = ClipboardHistoryViewModel(
            storage: storage,
            monitor: delegateMonitor,
            restorePasteboard: delegatePasteboard,
            settings: AppSettings(defaults: defaults),
            startsAutomatically: false
        )
        delegatePasteboard.clearContents()
        delegatePasteboard.setString("delegate insertion", forType: .string)
        await delegateMonitor.pollNowAndWait()
        for _ in 0..<100 where viewModel.items.isEmpty {
            try? await Task.sleep(for: .milliseconds(5))
        }
        XCTAssertEqual(viewModel.items.first?.text, "delegate insertion")
        viewModel.prepareForShutdown()
        await storage.close()
        defaults.removePersistentDomain(forName: suite)
        try? FileManager.default.removeItem(at: directory)
    }

    func testClipboardChangeDuringProcessingDropsStaleResult() async {
        let pasteboard = NSPasteboard(name: .init("ClipboardMonitorStale-\(UUID().uuidString)"))
        let processor = BlockingClipboardContentProcessor()
        let staleMonitor = ClipboardMonitor(
            pasteboard: pasteboard,
            processingService: processor
        )
        staleMonitor.delegate = self
        pasteboard.clearContents()
        pasteboard.setString("first", forType: .string)

        let poll = Task { await staleMonitor.pollNowAndWait() }
        await processor.waitUntilStarted()
        pasteboard.clearContents()
        pasteboard.setString("newer", forType: .string)
        await processor.resume(
            with: .text(
                value: "first",
                rtfData: nil,
                htmlData: nil,
                subtype: .plainText,
                hash: "first",
                sourceBundleIdentifier: nil
            )
        )
        await poll.value

        XCTAssertNil(receivedContent)
    }

    func clipboardMonitor(
        _ monitor: ClipboardMonitor,
        didReceive content: ClipboardContent,
        identity: ClipboardPasteboardIdentity
    ) {
        receivedContent = content
        receivedIdentity = identity
    }

    private func makePNGData() -> Data? {
        guard let bitmap = NSBitmapImageRep(
            bitmapDataPlanes: nil,
            pixelsWide: 2,
            pixelsHigh: 2,
            bitsPerSample: 8,
            samplesPerPixel: 4,
            hasAlpha: true,
            isPlanar: false,
            colorSpaceName: .deviceRGB,
            bytesPerRow: 8,
            bitsPerPixel: 32
        ) else { return nil }

        bitmap.setColor(
            NSColor(deviceRed: 0.1, green: 0.8, blue: 0.2, alpha: 1),
            atX: 0,
            y: 0
        )
        return bitmap.representation(using: .png, properties: [:])
    }
}

@MainActor
private final class MonitorTimerSchedulerSpy: RepeatingTimerScheduling {
    let token = MonitorTimerTokenSpy()
    private(set) var scheduleCount = 0
    private(set) var interval: TimeInterval?
    private(set) var tolerance: TimeInterval?
    private var action: (@MainActor () -> Void)?

    func schedule(
        interval: TimeInterval,
        tolerance: TimeInterval,
        action: @escaping @MainActor () -> Void
    ) -> any RepeatingTimerToken {
        scheduleCount += 1
        self.interval = interval
        self.tolerance = tolerance
        self.action = action
        return token
    }

    func fire() {
        action?()
    }
}

private final class MonitorTimerTokenSpy: RepeatingTimerToken, @unchecked Sendable {
    private(set) var cancelCount = 0

    func cancel() {
        cancelCount += 1
    }
}

private actor BlockingClipboardContentProcessor: ClipboardContentProcessing {
    private var didStart = false
    private var result: ClipboardContent?
    private var continuation: CheckedContinuation<ClipboardContent?, Never>?

    func process(
        _ rawContent: ClipboardRawContent,
        sourceBundleIdentifier: String?
    ) async -> ClipboardContent? {
        didStart = true
        if let result { return result }
        return await withCheckedContinuation { continuation = $0 }
    }

    func waitUntilStarted() async {
        while !didStart { await Task.yield() }
    }

    func resume(with result: ClipboardContent) {
        self.result = result
        continuation?.resume(returning: result)
        continuation = nil
    }
}
